- job:
    name: abrovink-tox-linters
    parent: tox-linters
    pre-run: playbooks/ensure-pip.yaml

- project:
    check:
      jobs: &id001
        - abrovink-tox-linters
    gate:
      jobs: *id001
